// Progressive enhancement only. index.html's film cards are static HTML
// (generated by scripts/build_static.py from data/films.json) so crawlers
// and no-JS clients see real content -- this file just wires up behavior
// on top of markup that already exists, and never fetches or rebuilds it.

// Only one film's audio plays at a time -- unmuting a clip mutes every
// other clip. Narration is different: most of these are silent films with
// just an orchestral score, so the narrator can read right over that score
// like a documentary voiceover. Listen ducks its own card's clip to a low
// volume instead of silencing it, and only cancels a narration running on
// a *different* card (still only one voice at a time).
function muteOtherVideos(exceptVideo) {
  document.querySelectorAll("video").forEach((v) => {
    if (v !== exceptVideo) v.muted = true;
  });
}

// Only one narration plays at a time, whether it's a pre-generated voice
// clip or the browser-TTS fallback. Whichever card started narrating last
// registers its own stop function here; starting a new one calls it first.
let activeStopNarration = null;

const CLIP_DUCK_VOLUME = 0.4;

// The reaction-cam's expression follows whichever card you're hovering.
function moodForGenre(genre) {
  const g = genre.toLowerCase();
  if (g.includes("horror") || g.includes("psychological")) return "scared";
  if (g.includes("screwball") || g.includes("romantic")) return "spit-take";
  if (g.includes("comedy")) return "laughing";
  if (g.includes("surreal")) return "dizzy";
  if (g.includes("science")) return "amazed";
  if (g.includes("western") || g.includes("action")) return "thrilled";
  if (g.includes("noir")) return "suspicious";
  if (g.includes("crime") || g.includes("exploitation") || g.includes("propaganda") || g.includes("melodrama") || g.includes("drama")) return "tense";
  return "neutral";
}

function setReactionMood(mood) {
  const cam = document.querySelector(".reaction-cam");
  if (cam) cam.dataset.mood = mood;
}

const speechSupported = "speechSynthesis" in window;

function enhanceCard(card) {
  const video = card.querySelector(".clip-video");
  const soundBadge = card.querySelector(".sound-badge");
  const narrateBtn = card.querySelector(".narrate-btn");
  const narrationAudio = card.querySelector(".narration-audio");
  const commentary = card.querySelector(".commentary");
  const captionTrack = card.querySelector(".clip-caption-track");
  const mood = moodForGenre(card.dataset.genre || "");

  // Anywhere else on the card (not a link or button -- those already have
  // their own destination: sound toggle, narration, the archive.org link,
  // the PD badge, or the title, which already links here too) takes you
  // to the film's own page, same as clicking the title.
  const titleLink = card.querySelector(".card-title-link");
  if (titleLink) {
    card.addEventListener("click", (event) => {
      if (event.target.closest("a, button")) return;
      window.location.href = titleLink.getAttribute("href");
    });
  }

  card.addEventListener("mouseenter", () => {
    video.play().catch(() => {});
    setReactionMood(mood);
  });
  card.addEventListener("mouseleave", () => {
    const ownNarrationPlaying = narrateBtn.classList.contains("narrating");
    if (!ownNarrationPlaying) video.pause();
    setReactionMood("neutral");
  });

  const syncSoundBadge = () => {
    soundBadge.textContent = video.muted ? "🔇" : "🔊";
    soundBadge.setAttribute("aria-label", video.muted ? "Play clip with sound" : "Mute clip");
  };
  syncSoundBadge();
  video.addEventListener("volumechange", syncSoundBadge);

  const toggleSound = (event) => {
    event.stopPropagation();
    if (video.muted) {
      const ownNarrationPlaying = narrateBtn.classList.contains("narrating");
      if (!ownNarrationPlaying && activeStopNarration) activeStopNarration();
      muteOtherVideos(video);
      video.muted = false;
      video.volume = ownNarrationPlaying ? CLIP_DUCK_VOLUME : 1;
      video.play().catch(() => {});
    } else {
      video.muted = true;
    }
  };
  // The video itself no longer toggles sound on click -- clicking it (like
  // clicking anywhere else non-interactive on the card) now goes to the
  // film's own page instead, where the sound/narration controls live.
  // The small sound-badge overlay is the exception, same as the narrate
  // button, watch link, and PD badge: it's a deliberate control, so it
  // keeps its own behavior instead of navigating.
  soundBadge.addEventListener("click", toggleSound);

  // While the real narration audio plays, the caption track's position
  // is driven directly by playback progress instead of free-running --
  // an approximation (there's no per-word timing data), but it means the
  // caption is always showing roughly the line being read rather than
  // scrolling at a fixed pace unrelated to where the narrator actually is.
  const syncCaptionToNarration = () => {
    if (!captionTrack || !narrationAudio.duration) return;
    const progress = Math.min(1, narrationAudio.currentTime / narrationAudio.duration);
    captionTrack.style.transform = `translateX(-${progress * 50}%)`;
  };

  const stopThisNarration = () => {
    narrationAudio.pause();
    narrationAudio.currentTime = 0;
    narrationAudio.removeEventListener("timeupdate", syncCaptionToNarration);
    if (captionTrack) {
      captionTrack.classList.remove("is-narrating");
      captionTrack.style.transform = "";
    }
    window.speechSynthesis.cancel();
    narrateBtn.classList.remove("narrating");
    narrateBtn.textContent = "🎧 Narration";
    video.volume = 1;
    if (activeStopNarration === stopThisNarration) activeStopNarration = null;
  };

  const speakFallback = () => {
    // The real audio failed to load, so there's no playback progress to
    // sync the caption to -- fall back to the plain decorative scroll
    // (hover to run it) rather than leaving it frozen at 0%.
    narrationAudio.removeEventListener("timeupdate", syncCaptionToNarration);
    if (captionTrack) {
      captionTrack.classList.remove("is-narrating");
      captionTrack.style.transform = "";
    }
    if (!speechSupported) {
      stopThisNarration();
      return;
    }
    const utterance = new SpeechSynthesisUtterance(commentary.textContent);
    utterance.rate = 0.85;
    utterance.onend = utterance.onerror = stopThisNarration;
    window.speechSynthesis.speak(utterance);
  };

  narrateBtn.addEventListener("click", () => {
    if (narrateBtn.classList.contains("narrating")) {
      stopThisNarration();
      return;
    }

    if (activeStopNarration) activeStopNarration(); // only one narration at a time
    muteOtherVideos(video); // ...and only one film's audio at a time
    video.muted = false;
    video.volume = CLIP_DUCK_VOLUME; // ducked so the narrator reads clearly over the score
    video.play().catch(() => {});

    narrateBtn.classList.add("narrating");
    narrateBtn.textContent = "⏸ Reading…";
    activeStopNarration = stopThisNarration;

    narrationAudio.currentTime = 0;
    narrationAudio.onended = stopThisNarration;
    narrationAudio.onerror = speakFallback;
    if (captionTrack) captionTrack.classList.add("is-narrating");
    narrationAudio.addEventListener("timeupdate", syncCaptionToNarration);
    narrationAudio.play().catch(speakFallback);
  });
}

// Shuffle the film order on every visit so the page doesn't look
// identical each time. Only the .card elements are reordered -- other
// grid children (the in-feed poster-strip ad slot) stay in their
// original slot rather than potentially landing first or last. This is
// purely a display-order change made after the page has already loaded
// with its real, static (and crawlable) order -- it doesn't affect what
// non-JS clients or crawlers see.
function shuffleGrid() {
  const grid = document.getElementById("grid");
  if (!grid) return; // a film's own page has one card and no #grid to shuffle
  const children = Array.from(grid.children);
  const cardSlots = [];
  const cards = [];
  children.forEach((el, i) => {
    if (el.classList.contains("card")) {
      cardSlots.push(i);
      cards.push(el);
    }
  });
  for (let i = cards.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [cards[i], cards[j]] = [cards[j], cards[i]];
  }
  cardSlots.forEach((slot, i) => {
    children[slot] = cards[i];
  });
  children.forEach((el) => grid.appendChild(el));
}

// Genre filter bar: buttons carry data-filter matching each card's
// data-category (see category_for_genre in scripts/build_static.py).
function enhanceFilterBar() {
  const bar = document.querySelector(".filter-bar");
  if (!bar) return;
  const buttons = Array.from(bar.querySelectorAll(".filter-btn"));
  const cards = Array.from(document.querySelectorAll(".card"));

  bar.addEventListener("click", (event) => {
    const btn = event.target.closest(".filter-btn");
    if (!btn) return;
    buttons.forEach((b) => b.classList.toggle("is-active", b === btn));
    const filter = btn.dataset.filter;
    cards.forEach((card) => {
      const matches = filter === "all" || card.dataset.category === filter;
      card.classList.toggle("is-filtered-out", !matches);
    });
  });
}

shuffleGrid();
document.querySelectorAll(".card").forEach(enhanceCard);
enhanceFilterBar();
